CREATE DATABASE IF NOT EXISTS INTEGRADORA;
USE INTEGRADORA;
SET NAMES 'utf8mb4';

CREATE TABLE ITEM(
	it_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
	it_name VARCHAR(30),
	it_price_out FLOAT, -- PRICE FOR CUSTOMERS
    it_price_in FLOAT, -- PRICE FOR PROVIDER
	it_brand SMALLINT,
	it_mt_body TINYINT,
    it_mt_sole TINYINT,
    it_mt_tongue TINYINT,
	it_color TINYINT,
	it_type TINYINT, -- Bota, zapato, etc.
	it_whose SMALLINT, -- GENDER
	it_release DATE
) ENGINE=InnoDB;

CREATE TABLE STOCK(
	st_id MEDIUMINT,
    st_item SMALLINT,
    st_location SMALLINT, -- EN DONDE ESTÁ, ALMACEN, ESTANTE, ETC.
    st_sizes TINYINT,
    st_stock TINYINT
) ENGINE=InnoDB;

CREATE TABLE ORDERS(
	or_id MEDIUMINT,
    or_provider SMALLINT,
    or_in DATE,
    or_full DATE,
    or_late BOOL,
    or_pay_type SMALLINT,
    or_paid BOOL
) ENGINE=InnoDB;

CREATE TABLE BRAND(
	br_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    br_nm VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE PROVIDER(
	pr_id SMALLINT,
    pr_nm VARCHAR(20),
    pr_account VARCHAR(16),
    pr_phone VARCHAR(10),
    pr_email VARCHAR(64),
    pr_website VARCHAR(64)
) ENGINE=InnoDB;

CREATE TABLE USERS(
	ur_id VARCHAR(6),
    ur_account_nm VARCHAR(16),
    ur_nm VARCHAR(16),
    ur_ln VARCHAR(32),
    ur_pw VARCHAR(64),
    ur_bank VARCHAR(16),
    ur_gender SMALLINT,
	ur_email VARCHAR(64)
) ENGINE=InnoDB;

CREATE TABLE ADDRESS(
	add_whose INT PRIMARY KEY AUTO_INCREMENT,
    add_number SMALLINT,
    add_street VARCHAR(20),
    add_postal VARCHAR(6),
    add_zone VARCHAR(16),
    add_city VARCHAR(16),
    add_country VARCHAR(2)
) ENGINE=InnoDB;

-- TABLAS DE CONVENIENCIA, NO SON PARTE DEL TRABAJO
CREATE TABLE MATERIAL(
	mt_id INT NOT NULL,
	mt_nm VARCHAR(10),
    CONSTRAINT PK_MATERIAL PRIMARY KEY (mt_id)
) ENGINE=InnoDB;
ALTER TABLE MATERIAL CHANGE mt_id mt_id INT AUTO_INCREMENT;

CREATE TABLE COLOR(
	cl_id INT NOT NULL,
	cl_nm VARCHAR(10),
    CONSTRAINT PK_COLOR PRIMARY KEY (cl_id)
) ENGINE=InnoDB;
ALTER TABLE COLOR CHANGE cl_id cl_id INT AUTO_INCREMENT;

CREATE TABLE TPE(
	tp_id INT NOT NULL,
	tp_nm VARCHAR(10),
    CONSTRAINT PK_TPE PRIMARY KEY (tp_id)
) ENGINE=InnoDB;
ALTER TABLE TPE CHANGE tp_id tp_id INT AUTO_INCREMENT;

CREATE TABLE PAY(
	py_id INT NOT NULL,
    py_nm VARCHAR(10),
    CONSTRAINT PK_PAY PRIMARY KEY (py_id)
) ENGINE=InnoDB;
ALTER TABLE PAY CHANGE py_id py_id INT AUTO_INCREMENT;



INSERT INTO ITEM VALUES (1,'Prueba',100.00,100.00,1,1,1,1,1,1,1,'1970-12-31');
INSERT INTO ORDERS VALUES(1,1,'1970-12-31','1970-12-31',true,1,false);
INSERT INTO STOCK VALUES(1,1,1,1,0);
INSERT INTO BRAND VALUES(1,'TEST',1);
INSERT INTO PROVIDER VALUES(1,'TEST','0000000000000000','0000000000','test@domain.dom','http://www.one.dom');
INSERT INTO USERS VALUES(1,'TEST','PASSWORD','0000000000000000',1,'test@domain.dom');
INSERT INTO ADDRESS VALUES (1,'STREET',100,11111,'COLONY','MEXICO');

-- PRIMARY KEYS
ALTER TABLE ITEM
ADD CONSTRAINT PK_ITEM
PRIMARY KEY (it_id);
ALTER TABLE STOCK
ADD CONSTRAINT PK_STOCK
PRIMARY KEY (st_id);
ALTER TABLE ORDERS
ADD CONSTRAINT PK_ORDERS
PRIMARY KEY (or_id);
ALTER TABLE BRAND
ADD CONSTRAINT PK_BRAND
PRIMARY KEY (br_id);
ALTER TABLE PROVIDER
ADD CONSTRAINT PK_PROVIDER
PRIMARY KEY (pr_id);
ALTER TABLE USERS
ADD CONSTRAINT PK_USERS
PRIMARY KEY (ur_id);
ALTER TABLE ADDRESS
ADD CONSTRAINT PK_ADDRESS
PRIMARY KEY (add_whose);


-- UNIQUE
ALTER TABLE ITEM ADD UNIQUE UQ_ITEM(it_id);
ALTER TABLE STOCK ADD UNIQUE UQ_STOCK(st_item);
ALTER TABLE ORDERS ADD UNIQUE UQ_ORDERS(or_id);
ALTER TABLE BRAND ADD UNIQUE UQ_BRAND(br_nm);
ALTER TABLE PROVIDER ADD UNIQUE UQ_PROVIDER(pr_nm,pr_account,pr_phone,pr_email,pr_website);
ALTER TABLE USERS ADD UNIQUE UQ_USERS(ur_account_nm,ur_bank,ur_email);
ALTER TABLE MATERIAL ADD UNIQUE UQ_MATERIAL(mt_id,mt_nm);
ALTER TABLE COLOR ADD UNIQUE UQ_COLOR(cl_id,cl_nm);
ALTER TABLE TPE ADD UNIQUE UQ_TPE(tp_id,tp_nm);
ALTER TABLE PAYMENT ADD UNIQUE UQ_COLOR(py_id,py_nm);